/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KolaciciRouteImport } from './routes/kolacici'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ONamaRouteImport } from './routes/o-nama'
import { Route as PolitikaPrivatnostiRouteImport } from './routes/politika-privatnosti'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UvjetiKoristenjaRouteImport } from './routes/uvjeti-koristenja'
import { Route as DokumentiIndexRouteImport } from './routes/dokumenti.index'
import { Route as DokumentiGodisnjaFinancijskaIzvjescaRouteImport } from './routes/dokumenti.godisnja-financijska-izvjesca'
import { Route as DokumentiJavnaNabavaRouteImport } from './routes/dokumenti.javna-nabava'
import { Route as DokumentiNadzorniOdborRouteImport } from './routes/dokumenti.nadzorni-odbor'
import { Route as DokumentiPravoNaPristupInformacijamaRouteImport } from './routes/dokumenti.pravo-na-pristup-informacijama'
import { Route as DokumentiSkupstinaRouteImport } from './routes/dokumenti.skupstina'
import { Route as DokumentiSponzorstvaIDonacijeRouteImport } from './routes/dokumenti.sponzorstva-i-donacije'
import { Route as DokumentiZastitaOsobnihPodatakaRouteImport } from './routes/dokumenti.zastita-osobnih-podataka'
import { Route as NovostiIndexRouteImport } from './routes/novosti.index'
import { Route as NovostiSlugRouteImport } from './routes/novosti.$slug'
import { Route as ObjektiIndexRouteImport } from './routes/objekti.index'
import { Route as ObjektiSlugRouteImport } from './routes/objekti.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KolaciciRoute = KolaciciRouteImport.update({
  id: '/kolacici',
  path: '/kolacici',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ONamaRoute = ONamaRouteImport.update({
  id: '/o-nama',
  path: '/o-nama',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaPrivatnostiRoute = PolitikaPrivatnostiRouteImport.update({
  id: '/politika-privatnosti',
  path: '/politika-privatnosti',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UvjetiKoristenjaRoute = UvjetiKoristenjaRouteImport.update({
  id: '/uvjeti-koristenja',
  path: '/uvjeti-koristenja',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentiIndexRoute = DokumentiIndexRouteImport.update({
  id: '/dokumenti/',
  path: '/dokumenti/',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentiGodisnjaFinancijskaIzvjescaRoute =
  DokumentiGodisnjaFinancijskaIzvjescaRouteImport.update({
    id: '/dokumenti/godisnja-financijska-izvjesca',
    path: '/dokumenti/godisnja-financijska-izvjesca',
    getParentRoute: () => rootRouteImport,
  } as any)
const DokumentiJavnaNabavaRoute = DokumentiJavnaNabavaRouteImport.update({
  id: '/dokumenti/javna-nabava',
  path: '/dokumenti/javna-nabava',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentiNadzorniOdborRoute = DokumentiNadzorniOdborRouteImport.update({
  id: '/dokumenti/nadzorni-odbor',
  path: '/dokumenti/nadzorni-odbor',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentiPravoNaPristupInformacijamaRoute =
  DokumentiPravoNaPristupInformacijamaRouteImport.update({
    id: '/dokumenti/pravo-na-pristup-informacijama',
    path: '/dokumenti/pravo-na-pristup-informacijama',
    getParentRoute: () => rootRouteImport,
  } as any)
const DokumentiSkupstinaRoute = DokumentiSkupstinaRouteImport.update({
  id: '/dokumenti/skupstina',
  path: '/dokumenti/skupstina',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentiSponzorstvaIDonacijeRoute =
  DokumentiSponzorstvaIDonacijeRouteImport.update({
    id: '/dokumenti/sponzorstva-i-donacije',
    path: '/dokumenti/sponzorstva-i-donacije',
    getParentRoute: () => rootRouteImport,
  } as any)
const DokumentiZastitaOsobnihPodatakaRoute =
  DokumentiZastitaOsobnihPodatakaRouteImport.update({
    id: '/dokumenti/zastita-osobnih-podataka',
    path: '/dokumenti/zastita-osobnih-podataka',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovostiIndexRoute = NovostiIndexRouteImport.update({
  id: '/novosti/',
  path: '/novosti/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovostiSlugRoute = NovostiSlugRouteImport.update({
  id: '/novosti/$slug',
  path: '/novosti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjektiIndexRoute = ObjektiIndexRouteImport.update({
  id: '/objekti/',
  path: '/objekti/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjektiSlugRoute = ObjektiSlugRouteImport.update({
  id: '/objekti/$slug',
  path: '/objekti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kolacici': typeof KolaciciRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uvjeti-koristenja': typeof UvjetiKoristenjaRoute
  '/dokumenti/godisnja-financijska-izvjesca': typeof DokumentiGodisnjaFinancijskaIzvjescaRoute
  '/dokumenti/javna-nabava': typeof DokumentiJavnaNabavaRoute
  '/dokumenti/nadzorni-odbor': typeof DokumentiNadzorniOdborRoute
  '/dokumenti/pravo-na-pristup-informacijama': typeof DokumentiPravoNaPristupInformacijamaRoute
  '/dokumenti/skupstina': typeof DokumentiSkupstinaRoute
  '/dokumenti/sponzorstva-i-donacije': typeof DokumentiSponzorstvaIDonacijeRoute
  '/dokumenti/zastita-osobnih-podataka': typeof DokumentiZastitaOsobnihPodatakaRoute
  '/novosti/$slug': typeof NovostiSlugRoute
  '/objekti/$slug': typeof ObjektiSlugRoute
  '/dokumenti/': typeof DokumentiIndexRoute
  '/novosti/': typeof NovostiIndexRoute
  '/objekti/': typeof ObjektiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kolacici': typeof KolaciciRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uvjeti-koristenja': typeof UvjetiKoristenjaRoute
  '/dokumenti/godisnja-financijska-izvjesca': typeof DokumentiGodisnjaFinancijskaIzvjescaRoute
  '/dokumenti/javna-nabava': typeof DokumentiJavnaNabavaRoute
  '/dokumenti/nadzorni-odbor': typeof DokumentiNadzorniOdborRoute
  '/dokumenti/pravo-na-pristup-informacijama': typeof DokumentiPravoNaPristupInformacijamaRoute
  '/dokumenti/skupstina': typeof DokumentiSkupstinaRoute
  '/dokumenti/sponzorstva-i-donacije': typeof DokumentiSponzorstvaIDonacijeRoute
  '/dokumenti/zastita-osobnih-podataka': typeof DokumentiZastitaOsobnihPodatakaRoute
  '/novosti/$slug': typeof NovostiSlugRoute
  '/objekti/$slug': typeof ObjektiSlugRoute
  '/dokumenti': typeof DokumentiIndexRoute
  '/novosti': typeof NovostiIndexRoute
  '/objekti': typeof ObjektiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kolacici': typeof KolaciciRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uvjeti-koristenja': typeof UvjetiKoristenjaRoute
  '/dokumenti/godisnja-financijska-izvjesca': typeof DokumentiGodisnjaFinancijskaIzvjescaRoute
  '/dokumenti/javna-nabava': typeof DokumentiJavnaNabavaRoute
  '/dokumenti/nadzorni-odbor': typeof DokumentiNadzorniOdborRoute
  '/dokumenti/pravo-na-pristup-informacijama': typeof DokumentiPravoNaPristupInformacijamaRoute
  '/dokumenti/skupstina': typeof DokumentiSkupstinaRoute
  '/dokumenti/sponzorstva-i-donacije': typeof DokumentiSponzorstvaIDonacijeRoute
  '/dokumenti/zastita-osobnih-podataka': typeof DokumentiZastitaOsobnihPodatakaRoute
  '/novosti/$slug': typeof NovostiSlugRoute
  '/objekti/$slug': typeof ObjektiSlugRoute
  '/dokumenti/': typeof DokumentiIndexRoute
  '/novosti/': typeof NovostiIndexRoute
  '/objekti/': typeof ObjektiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kolacici'
    | '/kontakt'
    | '/o-nama'
    | '/politika-privatnosti'
    | '/sitemap.xml'
    | '/uvjeti-koristenja'
    | '/dokumenti/godisnja-financijska-izvjesca'
    | '/dokumenti/javna-nabava'
    | '/dokumenti/nadzorni-odbor'
    | '/dokumenti/pravo-na-pristup-informacijama'
    | '/dokumenti/skupstina'
    | '/dokumenti/sponzorstva-i-donacije'
    | '/dokumenti/zastita-osobnih-podataka'
    | '/novosti/$slug'
    | '/objekti/$slug'
    | '/dokumenti/'
    | '/novosti/'
    | '/objekti/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kolacici'
    | '/kontakt'
    | '/o-nama'
    | '/politika-privatnosti'
    | '/sitemap.xml'
    | '/uvjeti-koristenja'
    | '/dokumenti/godisnja-financijska-izvjesca'
    | '/dokumenti/javna-nabava'
    | '/dokumenti/nadzorni-odbor'
    | '/dokumenti/pravo-na-pristup-informacijama'
    | '/dokumenti/skupstina'
    | '/dokumenti/sponzorstva-i-donacije'
    | '/dokumenti/zastita-osobnih-podataka'
    | '/novosti/$slug'
    | '/objekti/$slug'
    | '/dokumenti'
    | '/novosti'
    | '/objekti'
  id:
    | '__root__'
    | '/'
    | '/kolacici'
    | '/kontakt'
    | '/o-nama'
    | '/politika-privatnosti'
    | '/sitemap.xml'
    | '/uvjeti-koristenja'
    | '/dokumenti/godisnja-financijska-izvjesca'
    | '/dokumenti/javna-nabava'
    | '/dokumenti/nadzorni-odbor'
    | '/dokumenti/pravo-na-pristup-informacijama'
    | '/dokumenti/skupstina'
    | '/dokumenti/sponzorstva-i-donacije'
    | '/dokumenti/zastita-osobnih-podataka'
    | '/novosti/$slug'
    | '/objekti/$slug'
    | '/dokumenti/'
    | '/novosti/'
    | '/objekti/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KolaciciRoute: typeof KolaciciRoute
  KontaktRoute: typeof KontaktRoute
  ONamaRoute: typeof ONamaRoute
  PolitikaPrivatnostiRoute: typeof PolitikaPrivatnostiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UvjetiKoristenjaRoute: typeof UvjetiKoristenjaRoute
  DokumentiGodisnjaFinancijskaIzvjescaRoute: typeof DokumentiGodisnjaFinancijskaIzvjescaRoute
  DokumentiJavnaNabavaRoute: typeof DokumentiJavnaNabavaRoute
  DokumentiNadzorniOdborRoute: typeof DokumentiNadzorniOdborRoute
  DokumentiPravoNaPristupInformacijamaRoute: typeof DokumentiPravoNaPristupInformacijamaRoute
  DokumentiSkupstinaRoute: typeof DokumentiSkupstinaRoute
  DokumentiSponzorstvaIDonacijeRoute: typeof DokumentiSponzorstvaIDonacijeRoute
  DokumentiZastitaOsobnihPodatakaRoute: typeof DokumentiZastitaOsobnihPodatakaRoute
  NovostiSlugRoute: typeof NovostiSlugRoute
  ObjektiSlugRoute: typeof ObjektiSlugRoute
  DokumentiIndexRoute: typeof DokumentiIndexRoute
  NovostiIndexRoute: typeof NovostiIndexRoute
  ObjektiIndexRoute: typeof ObjektiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kolacici': {
      id: '/kolacici'
      path: '/kolacici'
      fullPath: '/kolacici'
      preLoaderRoute: typeof KolaciciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nama': {
      id: '/o-nama'
      path: '/o-nama'
      fullPath: '/o-nama'
      preLoaderRoute: typeof ONamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-privatnosti': {
      id: '/politika-privatnosti'
      path: '/politika-privatnosti'
      fullPath: '/politika-privatnosti'
      preLoaderRoute: typeof PolitikaPrivatnostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uvjeti-koristenja': {
      id: '/uvjeti-koristenja'
      path: '/uvjeti-koristenja'
      fullPath: '/uvjeti-koristenja'
      preLoaderRoute: typeof UvjetiKoristenjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/': {
      id: '/dokumenti/'
      path: '/dokumenti'
      fullPath: '/dokumenti/'
      preLoaderRoute: typeof DokumentiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/godisnja-financijska-izvjesca': {
      id: '/dokumenti/godisnja-financijska-izvjesca'
      path: '/dokumenti/godisnja-financijska-izvjesca'
      fullPath: '/dokumenti/godisnja-financijska-izvjesca'
      preLoaderRoute: typeof DokumentiGodisnjaFinancijskaIzvjescaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/javna-nabava': {
      id: '/dokumenti/javna-nabava'
      path: '/dokumenti/javna-nabava'
      fullPath: '/dokumenti/javna-nabava'
      preLoaderRoute: typeof DokumentiJavnaNabavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/nadzorni-odbor': {
      id: '/dokumenti/nadzorni-odbor'
      path: '/dokumenti/nadzorni-odbor'
      fullPath: '/dokumenti/nadzorni-odbor'
      preLoaderRoute: typeof DokumentiNadzorniOdborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/pravo-na-pristup-informacijama': {
      id: '/dokumenti/pravo-na-pristup-informacijama'
      path: '/dokumenti/pravo-na-pristup-informacijama'
      fullPath: '/dokumenti/pravo-na-pristup-informacijama'
      preLoaderRoute: typeof DokumentiPravoNaPristupInformacijamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/skupstina': {
      id: '/dokumenti/skupstina'
      path: '/dokumenti/skupstina'
      fullPath: '/dokumenti/skupstina'
      preLoaderRoute: typeof DokumentiSkupstinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/sponzorstva-i-donacije': {
      id: '/dokumenti/sponzorstva-i-donacije'
      path: '/dokumenti/sponzorstva-i-donacije'
      fullPath: '/dokumenti/sponzorstva-i-donacije'
      preLoaderRoute: typeof DokumentiSponzorstvaIDonacijeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/zastita-osobnih-podataka': {
      id: '/dokumenti/zastita-osobnih-podataka'
      path: '/dokumenti/zastita-osobnih-podataka'
      fullPath: '/dokumenti/zastita-osobnih-podataka'
      preLoaderRoute: typeof DokumentiZastitaOsobnihPodatakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novosti/': {
      id: '/novosti/'
      path: '/novosti'
      fullPath: '/novosti/'
      preLoaderRoute: typeof NovostiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novosti/$slug': {
      id: '/novosti/$slug'
      path: '/novosti/$slug'
      fullPath: '/novosti/$slug'
      preLoaderRoute: typeof NovostiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objekti/': {
      id: '/objekti/'
      path: '/objekti'
      fullPath: '/objekti/'
      preLoaderRoute: typeof ObjektiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objekti/$slug': {
      id: '/objekti/$slug'
      path: '/objekti/$slug'
      fullPath: '/objekti/$slug'
      preLoaderRoute: typeof ObjektiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KolaciciRoute: KolaciciRoute,
  KontaktRoute: KontaktRoute,
  ONamaRoute: ONamaRoute,
  PolitikaPrivatnostiRoute: PolitikaPrivatnostiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UvjetiKoristenjaRoute: UvjetiKoristenjaRoute,
  DokumentiGodisnjaFinancijskaIzvjescaRoute:
    DokumentiGodisnjaFinancijskaIzvjescaRoute,
  DokumentiJavnaNabavaRoute: DokumentiJavnaNabavaRoute,
  DokumentiNadzorniOdborRoute: DokumentiNadzorniOdborRoute,
  DokumentiPravoNaPristupInformacijamaRoute:
    DokumentiPravoNaPristupInformacijamaRoute,
  DokumentiSkupstinaRoute: DokumentiSkupstinaRoute,
  DokumentiSponzorstvaIDonacijeRoute: DokumentiSponzorstvaIDonacijeRoute,
  DokumentiZastitaOsobnihPodatakaRoute: DokumentiZastitaOsobnihPodatakaRoute,
  NovostiSlugRoute: NovostiSlugRoute,
  ObjektiSlugRoute: ObjektiSlugRoute,
  DokumentiIndexRoute: DokumentiIndexRoute,
  NovostiIndexRoute: NovostiIndexRoute,
  ObjektiIndexRoute: ObjektiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
