/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KolaciciRouteImport } from './routes/kolacici'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ONamaRouteImport } from './routes/o-nama'
import { Route as PolitikaPrivatnostiRouteImport } from './routes/politika-privatnosti'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UvjetiKoristenjaRouteImport } from './routes/uvjeti-koristenja'
import { Route as DokumentiIndexRouteImport } from './routes/dokumenti.index'
import { Route as DokumentiCjeniciRouteImport } from './routes/dokumenti.cjenici'
import { Route as DokumentiFinancijskaIzvjescaRouteImport } from './routes/dokumenti.financijska-izvjesca'
import { Route as DokumentiJavnaNabavaRouteImport } from './routes/dokumenti.javna-nabava'
import { Route as DokumentiNatjecajiRouteImport } from './routes/dokumenti.natjecaji'
import { Route as DokumentiPravilniciRouteImport } from './routes/dokumenti.pravilnici'
import { Route as NovostiIndexRouteImport } from './routes/novosti.index'
import { Route as NovostiSlugRouteImport } from './routes/novosti.$slug'
import { Route as ObjektiIndexRouteImport } from './routes/objekti.index'
import { Route as ObjektiSlugRouteImport } from './routes/objekti.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KolaciciRoute = KolaciciRouteImport.update({
  id: '/kolacici',
  path: '/kolacici',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ONamaRoute = ONamaRouteImport.update({
  id: '/o-nama',
  path: '/o-nama',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaPrivatnostiRoute = PolitikaPrivatnostiRouteImport.update({
  id: '/politika-privatnosti',
  path: '/politika-privatnosti',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UvjetiKoristenjaRoute = UvjetiKoristenjaRouteImport.update({
  id: '/uvjeti-koristenja',
  path: '/uvjeti-koristenja',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentiIndexRoute = DokumentiIndexRouteImport.update({
  id: '/dokumenti/',
  path: '/dokumenti/',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentiCjeniciRoute = DokumentiCjeniciRouteImport.update({
  id: '/dokumenti/cjenici',
  path: '/dokumenti/cjenici',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentiFinancijskaIzvjescaRoute =
  DokumentiFinancijskaIzvjescaRouteImport.update({
    id: '/dokumenti/financijska-izvjesca',
    path: '/dokumenti/financijska-izvjesca',
    getParentRoute: () => rootRouteImport,
  } as any)
const DokumentiJavnaNabavaRoute = DokumentiJavnaNabavaRouteImport.update({
  id: '/dokumenti/javna-nabava',
  path: '/dokumenti/javna-nabava',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentiNatjecajiRoute = DokumentiNatjecajiRouteImport.update({
  id: '/dokumenti/natjecaji',
  path: '/dokumenti/natjecaji',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentiPravilniciRoute = DokumentiPravilniciRouteImport.update({
  id: '/dokumenti/pravilnici',
  path: '/dokumenti/pravilnici',
  getParentRoute: () => rootRouteImport,
} as any)
const NovostiIndexRoute = NovostiIndexRouteImport.update({
  id: '/novosti/',
  path: '/novosti/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovostiSlugRoute = NovostiSlugRouteImport.update({
  id: '/novosti/$slug',
  path: '/novosti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjektiIndexRoute = ObjektiIndexRouteImport.update({
  id: '/objekti/',
  path: '/objekti/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjektiSlugRoute = ObjektiSlugRouteImport.update({
  id: '/objekti/$slug',
  path: '/objekti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kolacici': typeof KolaciciRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uvjeti-koristenja': typeof UvjetiKoristenjaRoute
  '/dokumenti/cjenici': typeof DokumentiCjeniciRoute
  '/dokumenti/financijska-izvjesca': typeof DokumentiFinancijskaIzvjescaRoute
  '/dokumenti/javna-nabava': typeof DokumentiJavnaNabavaRoute
  '/dokumenti/natjecaji': typeof DokumentiNatjecajiRoute
  '/dokumenti/pravilnici': typeof DokumentiPravilniciRoute
  '/novosti/$slug': typeof NovostiSlugRoute
  '/objekti/$slug': typeof ObjektiSlugRoute
  '/dokumenti/': typeof DokumentiIndexRoute
  '/novosti/': typeof NovostiIndexRoute
  '/objekti/': typeof ObjektiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kolacici': typeof KolaciciRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uvjeti-koristenja': typeof UvjetiKoristenjaRoute
  '/dokumenti/cjenici': typeof DokumentiCjeniciRoute
  '/dokumenti/financijska-izvjesca': typeof DokumentiFinancijskaIzvjescaRoute
  '/dokumenti/javna-nabava': typeof DokumentiJavnaNabavaRoute
  '/dokumenti/natjecaji': typeof DokumentiNatjecajiRoute
  '/dokumenti/pravilnici': typeof DokumentiPravilniciRoute
  '/novosti/$slug': typeof NovostiSlugRoute
  '/objekti/$slug': typeof ObjektiSlugRoute
  '/dokumenti': typeof DokumentiIndexRoute
  '/novosti': typeof NovostiIndexRoute
  '/objekti': typeof ObjektiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kolacici': typeof KolaciciRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uvjeti-koristenja': typeof UvjetiKoristenjaRoute
  '/dokumenti/cjenici': typeof DokumentiCjeniciRoute
  '/dokumenti/financijska-izvjesca': typeof DokumentiFinancijskaIzvjescaRoute
  '/dokumenti/javna-nabava': typeof DokumentiJavnaNabavaRoute
  '/dokumenti/natjecaji': typeof DokumentiNatjecajiRoute
  '/dokumenti/pravilnici': typeof DokumentiPravilniciRoute
  '/novosti/$slug': typeof NovostiSlugRoute
  '/objekti/$slug': typeof ObjektiSlugRoute
  '/dokumenti/': typeof DokumentiIndexRoute
  '/novosti/': typeof NovostiIndexRoute
  '/objekti/': typeof ObjektiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kolacici'
    | '/kontakt'
    | '/o-nama'
    | '/politika-privatnosti'
    | '/sitemap.xml'
    | '/uvjeti-koristenja'
    | '/dokumenti/cjenici'
    | '/dokumenti/financijska-izvjesca'
    | '/dokumenti/javna-nabava'
    | '/dokumenti/natjecaji'
    | '/dokumenti/pravilnici'
    | '/novosti/$slug'
    | '/objekti/$slug'
    | '/dokumenti/'
    | '/novosti/'
    | '/objekti/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kolacici'
    | '/kontakt'
    | '/o-nama'
    | '/politika-privatnosti'
    | '/sitemap.xml'
    | '/uvjeti-koristenja'
    | '/dokumenti/cjenici'
    | '/dokumenti/financijska-izvjesca'
    | '/dokumenti/javna-nabava'
    | '/dokumenti/natjecaji'
    | '/dokumenti/pravilnici'
    | '/novosti/$slug'
    | '/objekti/$slug'
    | '/dokumenti'
    | '/novosti'
    | '/objekti'
  id:
    | '__root__'
    | '/'
    | '/kolacici'
    | '/kontakt'
    | '/o-nama'
    | '/politika-privatnosti'
    | '/sitemap.xml'
    | '/uvjeti-koristenja'
    | '/dokumenti/cjenici'
    | '/dokumenti/financijska-izvjesca'
    | '/dokumenti/javna-nabava'
    | '/dokumenti/natjecaji'
    | '/dokumenti/pravilnici'
    | '/novosti/$slug'
    | '/objekti/$slug'
    | '/dokumenti/'
    | '/novosti/'
    | '/objekti/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KolaciciRoute: typeof KolaciciRoute
  KontaktRoute: typeof KontaktRoute
  ONamaRoute: typeof ONamaRoute
  PolitikaPrivatnostiRoute: typeof PolitikaPrivatnostiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UvjetiKoristenjaRoute: typeof UvjetiKoristenjaRoute
  DokumentiCjeniciRoute: typeof DokumentiCjeniciRoute
  DokumentiFinancijskaIzvjescaRoute: typeof DokumentiFinancijskaIzvjescaRoute
  DokumentiJavnaNabavaRoute: typeof DokumentiJavnaNabavaRoute
  DokumentiNatjecajiRoute: typeof DokumentiNatjecajiRoute
  DokumentiPravilniciRoute: typeof DokumentiPravilniciRoute
  NovostiSlugRoute: typeof NovostiSlugRoute
  ObjektiSlugRoute: typeof ObjektiSlugRoute
  DokumentiIndexRoute: typeof DokumentiIndexRoute
  NovostiIndexRoute: typeof NovostiIndexRoute
  ObjektiIndexRoute: typeof ObjektiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kolacici': {
      id: '/kolacici'
      path: '/kolacici'
      fullPath: '/kolacici'
      preLoaderRoute: typeof KolaciciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nama': {
      id: '/o-nama'
      path: '/o-nama'
      fullPath: '/o-nama'
      preLoaderRoute: typeof ONamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-privatnosti': {
      id: '/politika-privatnosti'
      path: '/politika-privatnosti'
      fullPath: '/politika-privatnosti'
      preLoaderRoute: typeof PolitikaPrivatnostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uvjeti-koristenja': {
      id: '/uvjeti-koristenja'
      path: '/uvjeti-koristenja'
      fullPath: '/uvjeti-koristenja'
      preLoaderRoute: typeof UvjetiKoristenjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/': {
      id: '/dokumenti/'
      path: '/dokumenti'
      fullPath: '/dokumenti/'
      preLoaderRoute: typeof DokumentiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/cjenici': {
      id: '/dokumenti/cjenici'
      path: '/dokumenti/cjenici'
      fullPath: '/dokumenti/cjenici'
      preLoaderRoute: typeof DokumentiCjeniciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/financijska-izvjesca': {
      id: '/dokumenti/financijska-izvjesca'
      path: '/dokumenti/financijska-izvjesca'
      fullPath: '/dokumenti/financijska-izvjesca'
      preLoaderRoute: typeof DokumentiFinancijskaIzvjescaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/javna-nabava': {
      id: '/dokumenti/javna-nabava'
      path: '/dokumenti/javna-nabava'
      fullPath: '/dokumenti/javna-nabava'
      preLoaderRoute: typeof DokumentiJavnaNabavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/natjecaji': {
      id: '/dokumenti/natjecaji'
      path: '/dokumenti/natjecaji'
      fullPath: '/dokumenti/natjecaji'
      preLoaderRoute: typeof DokumentiNatjecajiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenti/pravilnici': {
      id: '/dokumenti/pravilnici'
      path: '/dokumenti/pravilnici'
      fullPath: '/dokumenti/pravilnici'
      preLoaderRoute: typeof DokumentiPravilniciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novosti/': {
      id: '/novosti/'
      path: '/novosti'
      fullPath: '/novosti/'
      preLoaderRoute: typeof NovostiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novosti/$slug': {
      id: '/novosti/$slug'
      path: '/novosti/$slug'
      fullPath: '/novosti/$slug'
      preLoaderRoute: typeof NovostiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objekti/': {
      id: '/objekti/'
      path: '/objekti'
      fullPath: '/objekti/'
      preLoaderRoute: typeof ObjektiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objekti/$slug': {
      id: '/objekti/$slug'
      path: '/objekti/$slug'
      fullPath: '/objekti/$slug'
      preLoaderRoute: typeof ObjektiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KolaciciRoute: KolaciciRoute,
  KontaktRoute: KontaktRoute,
  ONamaRoute: ONamaRoute,
  PolitikaPrivatnostiRoute: PolitikaPrivatnostiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UvjetiKoristenjaRoute: UvjetiKoristenjaRoute,
  DokumentiCjeniciRoute: DokumentiCjeniciRoute,
  DokumentiFinancijskaIzvjescaRoute: DokumentiFinancijskaIzvjescaRoute,
  DokumentiJavnaNabavaRoute: DokumentiJavnaNabavaRoute,
  DokumentiNatjecajiRoute: DokumentiNatjecajiRoute,
  DokumentiPravilniciRoute: DokumentiPravilniciRoute,
  NovostiSlugRoute: NovostiSlugRoute,
  ObjektiSlugRoute: ObjektiSlugRoute,
  DokumentiIndexRoute: DokumentiIndexRoute,
  NovostiIndexRoute: NovostiIndexRoute,
  ObjektiIndexRoute: ObjektiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
